# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ff528bf684b15b42026029c33ab2338590954f274e3a2c8b3e809ad4d24fef0ab56ea1e86fb5b34d8ba321d9bbcff833ef6ec85093f6ea2209c1d643cd2c65e

test:
  secret_key_base: c04645041c67c26ebcaee4dfc0f77fbfdb7182b2f58e1d6360915788e18c35efd1cded75916c6d7bd80a793a50a6c817bdc699def2d45cdda1bbbcb013f1926a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
